version: '3'

services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGODB_URI=mongodb://mongo:27017/virtual_lawyer
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRE=30d
      - JWT_COOKIE_EXPIRE=30
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    depends_on:
      - mongo
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  mongo-data: